### ISSUE TITLE
Clarify Licensing

### ISSUE THREAD

**Issue by donn** [zeroc-ice/mcpp#4]
Files by Kiyoshi Matsui appear to still be under the MIT License, but files such as `Makefile` simply state:

```
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
```

Can I assume these files are also licensed under the MIT license? RSVP.

**Comment by pepone** [comment]
Yes, different Copyright same license

**Comment by donn** [comment]
👍 I'll create a PR that fixes the headers then.

**Comment by pepone** [comment]
Hi Donn,

I think nothing needs to be fixed, the Makefile file has ZeroC copyright and that is fine, the whole thing is licensed under MIT and there is no conflict here.

**Comment by donn** [comment]
While that is true, there is no explicit legal statement that your changes are also covered under the MIT license: the License file only shows Kiyoshi Matsui's copyright. Absent this statement, the code falls back to the harshest possible license, i.e., the GitHub terms and conditions for sharing projects. Which would make mcpp very difficult to use in my projects (and I want to!)

I didn't change the file headers, but did add an explicit statement in #5. I'd appreciate if you can take a look at it- and sorry for bothering you about an older project. :)

**Comment by bernardnormier** [comment]
Donn, the current license file and copyright statements are fine.

The entire repo is licensed as per its license file: https://github.com/zeroc-ice/mcpp/blob/master/LICENSE
It's actually the BSD-2-Clause license, not the MIT license: https://opensource.org/licenses/BSD-2-Clause

This repo is not meant to be a supported fork of mcpp - it's a fork for the Slice compilers. If you want to use mcpp for other purposes, I suggest you pick instead the Debian/Ubuntu code: https://packages.ubuntu.com/hirsute/mcpp. We use this Ubuntu mcpp on Ubuntu instead of our own fork.

**Comment by donn** [comment]
Well, thanks regardless.
